using UnityEngine;

namespace BlackHoleEffect
{
    /// <summary>
    /// Procedural cosmic soundscape — no audio assets required.
    ///   * Deep B♭ drone (a nod to the Perseus cluster black hole, whose real
    ///     "note" is a B♭ 57 octaves below middle C).
    ///   * Slowly crossfading ambient pad chords in B♭ minor (detuned sine
    ///     pairs, long equal-power fades) — calm, mysterious, spacey.
    ///   * Sparse pentatonic shimmer notes with long decays.
    ///   * Plasma hiss panned toward the approaching (Doppler-bright) side.
    /// Generated by a streaming stereo AudioClip. M key toggles mute.
    /// </summary>
    [RequireComponent(typeof(AudioSource))]
    public class BlackHoleAudio : MonoBehaviour
    {
        [Range(0f, 1f)] public float volume = 0.22f;
        public bool muted;

        const int SampleRate = 48000;
        const double Tau = 2.0 * System.Math.PI;

        // B♭ minor world: Bbm, Gb, Ebm, Fm (frequencies in Hz).
        static readonly double[][] Chords =
        {
            new[] { 58.27, 87.31, 116.54, 138.59, 174.61 },  // Bb1 F2 Bb2 Db3 F3
            new[] { 46.25, 92.50, 138.59, 185.00, 233.08 },  // Gb1 Gb2 Db3 Gb3 Bb3
            new[] { 51.91, 77.78, 116.54, 155.56, 185.00 },  // Eb1 Eb2 Bb2 Eb3 Gb3
            new[] { 58.27, 87.31, 130.81, 174.61, 207.65 },  // Bb1 F2 C3  F3  Ab3
        };
        static readonly double[] ShimmerNotes = { 466.16, 554.37, 698.46, 830.61, 932.33 }; // Bb4 Db5 F5 Ab5 Bb5
        const double ChordSeconds = 16.0;
        const double FadeSeconds = 6.0;

        AudioSource source;
        readonly double[] phaseA = new double[10]; // current chord, 5 voices x2 detune
        readonly double[] phaseB = new double[10]; // next chord
        double dronePhase1, dronePhase2, lfoPhase;
        double chordTimer;
        int chordIndex;
        float lowpassState;
        uint rng = 0x9E3779B9;

        // shimmer state
        double shimmerPhase, shimmerEnv, shimmerFreq;
        double shimmerCountdown = 4.0;

        float NextRand() // xorshift, audio-thread safe, no allocation
        {
            rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5;
            return (rng & 0xFFFFFF) / (float)0x1000000;
        }

        void Awake()
        {
            source = GetComponent<AudioSource>();
            var clip = AudioClip.Create("CosmicSoundscape", SampleRate, 2, SampleRate, true, OnRead);
            source.clip = clip;
            source.loop = true;
            source.spatialBlend = 0f;
            source.playOnAwake = false;
        }

        void Start()
        {
            if (Application.isPlaying) source.Play();
        }

        void Update()
        {
            if (source != null) { source.mute = muted; source.volume = 1f; }
        }

        void OnRead(float[] data)
        {
            int frames = data.Length / 2;
            double dt = 1.0 / SampleRate;

            var cur = Chords[chordIndex];
            var nxt = Chords[(chordIndex + 1) % Chords.Length];

            for (int f = 0; f < frames; f++)
            {
                // ---- chord scheduling with equal-power crossfade ----
                chordTimer += dt;
                double fade = (chordTimer - (ChordSeconds - FadeSeconds)) / FadeSeconds;
                fade = fade < 0 ? 0 : (fade > 1 ? 1 : fade);
                float gainCur = Mathf.Cos((float)fade * Mathf.PI * 0.5f);
                float gainNxt = Mathf.Sin((float)fade * Mathf.PI * 0.5f);
                if (chordTimer >= ChordSeconds)
                {
                    chordTimer = 0;
                    chordIndex = (chordIndex + 1) % Chords.Length;
                    cur = Chords[chordIndex];
                    nxt = Chords[(chordIndex + 1) % Chords.Length];
                    for (int v = 0; v < 10; v++) { phaseA[v] = phaseB[v]; phaseB[v] = 0; }
                }

                float pad = 0f;
                for (int v = 0; v < 5; v++)
                {
                    phaseA[v * 2] += Tau * cur[v] * dt;
                    phaseA[v * 2 + 1] += Tau * cur[v] * 1.004 * dt;
                    pad += gainCur * 0.5f * ((float)System.Math.Sin(phaseA[v * 2]) + (float)System.Math.Sin(phaseA[v * 2 + 1]));
                    phaseB[v * 2] += Tau * nxt[v] * dt;
                    phaseB[v * 2 + 1] += Tau * nxt[v] * 1.004 * dt;
                    pad += gainNxt * 0.5f * ((float)System.Math.Sin(phaseB[v * 2]) + (float)System.Math.Sin(phaseB[v * 2 + 1]));
                }
                pad *= 0.09f;

                // ---- B♭ drone with slow breathing ----
                lfoPhase += Tau * 0.045 * dt;
                float breathe = 0.65f + 0.35f * (float)System.Math.Sin(lfoPhase);
                dronePhase1 += Tau * 58.27 * dt;
                dronePhase2 += Tau * 116.54 * dt;
                float drone = (0.5f * (float)System.Math.Sin(dronePhase1)
                             + 0.18f * (float)System.Math.Sin(dronePhase2)) * breathe * 0.5f;

                // ---- plasma hiss (lowpassed noise), Doppler-panned left ----
                float white = NextRand() * 2f - 1f;
                lowpassState += 0.04f * (white - lowpassState);
                float hiss = lowpassState * 0.14f;

                // ---- sparse shimmer notes ----
                shimmerCountdown -= dt;
                if (shimmerCountdown <= 0)
                {
                    shimmerCountdown = 6.0 + NextRand() * 8.0;
                    shimmerFreq = ShimmerNotes[(int)(NextRand() * ShimmerNotes.Length) % ShimmerNotes.Length];
                    shimmerEnv = 1.0;
                    shimmerPhase = 0;
                }
                float shimmer = 0f;
                if (shimmerEnv > 0.001)
                {
                    shimmerPhase += Tau * shimmerFreq * dt;
                    shimmerEnv *= 1.0 - 0.9 * dt; // ~4 s decay
                    shimmer = (float)(System.Math.Sin(shimmerPhase) * shimmerEnv) * 0.045f;
                }

                float mono = (pad + drone + shimmer) * volume;
                float hissV = hiss * volume;
                data[f * 2] = mono + hissV * 1.35f;   // left = approaching side
                data[f * 2 + 1] = mono + hissV * 0.65f;
            }
        }
    }
}
